image: python:alpine

before_script:
  - pip install -i https://mirrors.zju.edu.cn/pypi/web/simple mkdocs && mkdocs --version
  - pip install -i https://mirrors.zju.edu.cn/pypi/web/simple mkdocs-material

pages:
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - main