image: python:3.10.4-buster

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - mkdocs build -d public --site-dir test
  artifacts:
    paths:
      - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - mkdocs build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
