site_name: M.T.Dickens' Blog
site_url: "https://blog.mtds.eu.org"
site_author: "mtdickens"
site_description: "mtdicken's blog"

nav:
  - 主页: "index.md"
  - 建议:
      - 丁尧相老师:
          - 总体建议:
              - 书籍建议: "Advice/Professors/Yaoxiang Ding/advice-on-books.md"
              - 课程建议: "Advice/Professors/Yaoxiang Ding/advice-on-courses.md"
          - 2023 年:
              - 1 月:
                  - 阅读建议: "Advice/Professors/Yaoxiang Ding/advice on reading.md"
                  - 听讲记录: "Advice/Professors/Yaoxiang Ding/23/01/note.md"
              - 2 月:
                  - 听讲 23-02-23: "Advice/Professors/Yaoxiang Ding/23/02/23-02-23.md"
              - 3 月:
                  - 线下交流 23-03-18: "Advice/Professors/Yaoxiang Ding/23/03/23-03-18.md"
                  - 线下交流 23-03-25: "Advice/Professors/Yaoxiang Ding/23/03/23-03-25.md"
              - 5 月:
                  - 线下交流 23-05-05: "Advice/Professors/Yaoxiang Ding/23/05/23-05-05.md"
  - 技术:
      - 网络:
          - Cloudflare:
              - Cloudflare Pages 部署: "Technology/Internet/Cloudflare/Cloudflare Pages deployment.md"
          - SSH:
              - 使用密钥登录 ssh: "Technology/Internet/SSH/ssh-via-password-or-public-key.md"
              - Mosh 使用指南: "Technology/Internet/SSH/mosh-guide.md"
          - JS:
              - 浙大 GPA 计算脚本: "Technology/Internet/JS/GPA-script.md"
      - 编程语言:
          - Haskell:
              - How to use GHCup and Stack: "Technology/Haskell/how-to-use-ghcup-and-stack.md"
          - Python:
              - Python 插件:
                  - yt-dlp: "Technology/Python/yt-dlp.md"
              - Python tips: "Technology/Python/python-tips.md"
      - 软件:
          - VS Code:
              - ssh:
                  - VS Code 中为 ssh 配置代理: "Technology/VS-Code/ssh/ssh-via-proxy.md"
              - 插件推荐: "Technology/VS-Code/plugins-recommendation.md"
              - 提高文件树的可读性: "Technology/VS-Code/readable-explorer-tree/readable-explorer-tree.md"
      - Git:
          - Git 备忘录: "Technology/Git/git-tips.md"
          - Git-crypt 插件: "Technology/Git/git-crypt.md"
      - GNU:
          - GDB 备忘录: "Technology/gdb-tips.md"
      - Docker:
          - Docker 备忘录: "Technology/docker-tips.md"
      - 博客:
          - MkDocs:
              - 插件:
                  - mkdocs-encryptcontent 插件使用: "Technology/OS/Linux/mkdocs/plugins/mkdocs-encryptcontent.md"
      - VPS:
          - Microsoft Azure:
              - Azure 使用避雷: "Technology/VPS/Azure/azure-using-guide.md"
              - Azure 如何启用 root 用户登录: "Technology/VPS/Azure/ssh-via-root.md"
      - 操作系统:
          - Linux:
              - FAQ:
                  - 设置 Linux ipv4 优先的方法: "Technology/OS/Linux/FAQ/ipv4-first.md"
                  - Ubuntu 中更改 Shell: "Technology/OS/Linux/FAQ/change shell in Ubuntu.md"
              - Linux tips: "Technology/OS/Linux/Linux-tips.md"
              - Linux 常用软件: "Technology/OS/Linux/frequently-used-softwares-in-Linux.md"
              - Linux 必备软件: "Technology/OS/Linux/must-install-softwares-in-Linux.md"
              - Linux 各个主要目录的作用: "Technology/OS/Linux/FAQ/Linux-directories.md"
              - Linux 软件介绍:
                  - fail2ban 使用: "Technology/OS/Linux/Softwares/fail2ban/fail2ban.md"
                  - rlwrap 使用: "Technology/OS/Linux/Softwares/rlwrap/rlwrap-manual.md"
                  - V2rayA 使用: "Technology/OS/Linux/Softwares/v2raya/v2raya.md"
          - Windows:
              - Windows tips: "Technology/OS/Windows/faq.md"
      - 浏览器:
          - Chrome 插件:
              - Google 输入工具: "Technology/Chrome-addons/google-input-tools.md"
      - PDF 处理:
          - 给 PDF 文件添加目录: "Technology/PDF/Add-contents-to-a-PDF-file.md"
          - Sioyek 使用指南: "Technology/PDF/a-short-guide-of-sioyek.md"
      - 网络代理:
          - V2Ray+ws+tls+nginx(web) 全解析: "Technology/Proxy/v2ray-ws-tls-web.md"
  - 计算机科学:
      - 2023 年:
          - 图灵机代码: "CS/23/codes-for-turing-machine.md"
          - 和 ChatGPT 的一次交流: "CS/23/chatgpt-mutual-communication.md"
          - 神经网络简介: "CS/23/introduction-to-neuron-network/introduction-to-neuron-network.md"
          - 如何阅读源码: "CS/23/how-to-read-source-code.md"
  - 数学:
      - 2023 年:
          - MIT牛人解说数学体系: "Mathematics/23/mathematical-system-explained-by-MIT-master.md"
          - 图解对偶映射: "Mathematics/23/dual-map-explained.md"
          - Youtube 的数学频道: "Mathematics/23/math-channels-on-youtube.md"
          - 知乎用户收集: "Mathematics/23/good-users-on-zhihu.md"
  - 随记:
      - 2023 年:
          - 学习常用网站: "Notes/23/often-used-websites-in-study.md"
          - 关于在 Chatgpt 上执行代码: "Notes/23/run-code-on-chat-gpt.md"
          - 如何高效阅读论文: "Notes/23/how-to-read-papers-efficiently.md"
          - 如何祛费拉化: "Notes/23/how-to-not-be-a-fellah.md"
  - 转载:
      - Hostloc:
          - U1S1 樱花妹真的不一样……: "Repost/hostloc/23-10-08.md"
      - 知乎:
          - 库，框架，架构，平台的区别: "Repost/zhihu/distinguish-between-library-framework-architecture-platform.md"
          - 拓扑数据分析 - 持续同调:
              - 一: "Repost/zhihu/topological-data-analysis/topological-data-analysis-homology (1).md"
              - 二: "Repost/zhihu/topological-data-analysis/topological-data-analysis-homology (2).md"
              - 三: "Repost/zhihu/topological-data-analysis/topological-data-analysis-homology (3).md"
              - 四: "Repost/zhihu/topological-data-analysis/topological-data-analysis-homology (4).md"
              - 五（上）: "Repost/zhihu/topological-data-analysis/topological-data-analysis-homology (5a).md"
              - 五（下）: "Repost/zhihu/topological-data-analysis/topological-data-analysis-homology (5b).md"
          - 什么是代数: "Repost/zhihu/what-is-algebra.md"
          - 论数学教育: "Repost/zhihu/on-teaching-mathematics-v-i-arnold.md"
  - 音乐:
      - 特辑：前苏联:
          - 加盟共和国国歌选: "Music/USSR/national-anthems-of-union-republics.md"
      - 阿富汗: "Music/Afghanistan.md"
      - 伊朗: "Music/Iran.md"
      - 高加索:
          - 阿塞拜疆: "Music/Caucasia/Azerbaijan.md"
      - 中亚五国: "Music/Central-asia.md"

theme:
  name: "material"
  palette: #切换昼夜模式的颜色，审美差就用默认，专业点就自定义
    - media: "(prefers-color-scheme: light)"
      scheme: default #配色方案：浅色模式
      primary: Brown #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      accent: Brown #强调色，默认蓝，可以交互的元素如悬停链接、按钮和滚动条
      toggle:
        icon: material/weather-sunny #图标，太阳
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate #配色方案：深色模式
      # primary: Brown  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      toggle:
        icon: material/weather-night #图标，月亮
        name: Switch to light mode
  features:
    - content.code.copy
  custom_dir: overrides

plugins:
  - search
  - mermaid2
  - encryptcontent:
      # use_secret: 'ENCRYPTCONTENT_PASSWORD'
      remember_password: True
      title_prefix: "[LOCKED]"
      summary: "This content is PROTECTED"
      encryption_info_message: "Contact me for access to this page."

markdown_extensions:
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
