site_name: M.T.Dickens' Blog
site_url: "https://blog.mtds.eu.org"
site_author: "mtdickens"
site_description: "mtdicken's blog"

nav:
- 主页: 'main_page.md'
- 建议:
  - 丁尧相老师:
    - 总体建议:
      - 书籍建议: 'Advice/Professors/Yaoxiang Ding/advice_on_books.md'
      - 课程建议: 'Advice/Professors/Yaoxiang Ding/advice_on_courses.md'
    - 2023 年:
      - 1 月:
        - 阅读建议: 'Advice/Professors/Yaoxiang Ding/advice on reading.md'
        - 听讲记录: 'Advice/Professors/Yaoxiang Ding/23/01/note.md'
      - 2 月:
        - 听讲 23-02-23: 'Advice/Professors/Yaoxiang Ding/23/02/23-02-23.md'
      - 3 月:
        - 线下交流 23-03-18: 'Advice/Professors/Yaoxiang Ding/23/03/23-03-18.md'
        - 线下交流 23-03-25: 'Advice/Professors/Yaoxiang Ding/23/03/23-03-25.md'
- 技术:
  - 故障排除: 
    - Cloudflare Pages 部署: 'Technology/Trouble Shooting/Cloudflare Pages deployment.md'
    - Ubuntu 中更改 Shell: 'Technology/Trouble Shooting/change shell in Ubuntu.md'
  - 使用技巧:
    - VS Code:
      - 插件推荐: 'Technology/VS_Code/plugins_recommendation.md'
      - 提高文件树的可读性: 'Technology/VS_Code/readable_explorer_tree/readable_explorer_tree.md'
    - MkDocs 使用:
      - 插件:
        - mkdocs_encryptcontent 插件使用: 'Technology/Linux/mkdocs/plugins/mkdocs_encryptcontent.md'
    - VPS:
      - 设置 VPS ipv4 优先的方法: 'Technology/VPS/ipv4_first.md'
      - Microsoft Azure:
        - Azure 使用避雷: 'Technology/VPS/Azure/azure_using_guide.md'
        - Azure 如何启用 root 用户登录: 'Technology/VPS/Azure/ssh_via_root.md'
    - Linux: 
      - Linux tips: 'Technology/Linux/Linux_tips.md'
      - Linux 常用软件: 'Technology/Linux/frequently_used_softwares_in_Linux.md'
      - Linux 必备软件: 'Technology/Linux/must-install_softwares_in_Linux.md'
      - Linux 软件介绍:
        - fail2ban 使用: 'Technology/Linux/Softwares/fail2ban/fail2ban.md'
        - rlwrap 使用: 'Technology/Linux/Softwares/rlwrap/rlwrap_manual.md'
    - Chrome 插件:
      - Google 输入工具: 'Technology/Chrome_addons/google-input-tools.md'
    - Git 备忘录: 'Technology/git_tips.md'
    - GDB 备忘录: 'Technology/gdb_tips.md'
    - Docker 备忘录: 'Technology/docker_tips.md'
    - PDF 处理:
      - 给 PDF 文件添加目录: 'Technology/PDF/Add_contents_to_a_PDF_file.md'
- 计算机科学:
  - 2023 年:
    - 图灵机代码: 'CS/23/codes_for_turing_machine.md'
    - 和 ChatGPT 的一次交流: 'CS/23/chatgpt_mutual_communication.md'
- 数学:
  - 2023 年: 
    - MIT牛人解说数学体系: 'Mathematics/23/mathematical_system_explained_by_MIT_master.md' 
    - 图解对偶映射: 'Mathematics/23/dual_map_explained.md' 
- 随记:
  - 2023 年:
    - 学习常用网站: 'Notes/23/often_used_websites_in_study.md'
    - 关于在 Chatgpt 上执行代码: 'Notes/23/run_code_on_chat_gpt.md'
    - 如何高效阅读论文: 'Notes/23/how_to_read_papers_efficiently.md'

theme:
  name: 'material'
  palette:     #切换昼夜模式的颜色，审美差就用默认，专业点就自定义
    - media: "(prefers-color-scheme: light)" 
      scheme: default  #配色方案：浅色模式
      primary: Brown  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      accent: Brown  #强调色，默认蓝，可以交互的元素如悬停链接、按钮和滚动条
      toggle:
        icon: material/weather-sunny #图标，太阳
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  
      scheme: slate  #配色方案：深色模式
      # primary: Brown  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      toggle:
        icon: material/weather-night  #图标，月亮
        name: Switch to light mode

plugins:
  - search
  - mermaid2
  - encryptcontent:
      # use_secret: 'ENCRYPTCONTENT_PASSWORD'
      remember_password: True 
      default_expire_delay: 24
      title_prefix: '[LOCKED]'
      summary: 'This content is PROTECTED'
      encryption_info_message: 'Contact me for access to this page.'      

markdown_extensions:
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js