site_name: M.T.Dickens' Blog
site_url: "https://blog.mtds.eu.org"
site_author: "mtdickens"
site_description: "mtdicken's blog"

nav:
  - 主页: "index.md"
  - 建议:
      - 丁尧相老师:
          - 总体建议:
              - 书籍建议: "Advice/Professors/Yaoxiang Ding/advice-on-books.md"
              - 课程建议: "Advice/Professors/Yaoxiang Ding/advice-on-courses.md"
          - 2023 年:
              - 1 月:
                  - 阅读建议: "Advice/Professors/Yaoxiang Ding/advice on reading.md"
                  - 听讲记录: "Advice/Professors/Yaoxiang Ding/23/01/note.md"
              - 2 月:
                  - 听讲 23-02-23: "Advice/Professors/Yaoxiang Ding/23/02/23-02-23.md"
              - 3 月:
                  - 线下交流 23-03-18: "Advice/Professors/Yaoxiang Ding/23/03/23-03-18.md"
                  - 线下交流 23-03-25: "Advice/Professors/Yaoxiang Ding/23/03/23-03-25.md"
              - 5 月:
                  - 线下交流 23-05-05: "Advice/Professors/Yaoxiang Ding/23/05/23-05-05.md"
  - 技术:
      - 网络:
          - Cloudflare:
              - Cloudflare Pages 部署: "Technology/Internet/Cloudflare/Cloudflare Pages deployment.md"
          - SSH:
              - 使用密钥登录 ssh: "Technology/Internet/SSH/ssh-via-password-or-public-key.md"
              - Mosh 使用指南: "Technology/Internet/SSH/mosh-guide.md"
          - JS:
              - 浙大 GPA 计算脚本: "Technology/Internet/JS/GPA-script.md"
      - 编程语言:
          - Haskell:
              - How to use GHCup and Stack: "Technology/Haskell/how-to-use-ghcup-and-stack.md"
          - Python:
              - Python 插件:
                  - yt-dlp: "Technology/Python/yt-dlp.md"
              - Python tips: "Technology/Python/python-tips.md"
              - SymPy 使用指南: "Technology/Python/sympy-guide.md"
      - 软件:
          - VS Code:
              - ssh:
                  - VS Code 中为 ssh 配置代理: "Technology/VS-Code/ssh/ssh-via-proxy.md"
              - 插件推荐: "Technology/VS-Code/plugins-recommendation.md"
              - 提高文件树的可读性: "Technology/VS-Code/readable-explorer-tree/readable-explorer-tree.md"
      - Git:
          - Git 备忘录: "Technology/Git/git-tips.md"
          - Git-crypt 插件: "Technology/Git/git-crypt.md"
      - CMake:
          - CMake 教程: "Technology/cmake/tutorial.md"
      - GNU:
          - GDB 备忘录: "Technology/gdb-tips.md"
      - Docker:
          - Docker 备忘录: "Technology/docker-tips.md"
      - 博客:
          - MkDocs:
              - 插件:
                  - mkdocs-encryptcontent 插件使用: "Technology/OS/Linux/mkdocs/plugins/mkdocs-encryptcontent.md"
      - VPS:
          - Microsoft Azure:
              - Azure 使用避雷: "Technology/VPS/Azure/azure-using-guide.md"
              - Azure 如何启用 root 用户登录: "Technology/VPS/Azure/ssh-via-root.md"
      - 操作系统:
          - Linux:
              - FAQ:
                  - 设置 Linux ipv4 优先的方法: "Technology/OS/Linux/FAQ/ipv4-first.md"
                  - Ubuntu 中更改 Shell: "Technology/OS/Linux/FAQ/change shell in Ubuntu.md"
              - Linux tips: "Technology/OS/Linux/Linux-tips.md"
              - Linux 常用软件: "Technology/OS/Linux/frequently-used-softwares-in-Linux.md"
              - Linux 必备软件: "Technology/OS/Linux/must-install-softwares-in-Linux.md"
              - Linux 各个主要目录的作用: "Technology/OS/Linux/FAQ/Linux-directories.md"
              - Linux 软件介绍:
                  - fail2ban 使用: "Technology/OS/Linux/Softwares/fail2ban/fail2ban.md"
                  - rlwrap 使用: "Technology/OS/Linux/Softwares/rlwrap/rlwrap-manual.md"
                  - V2rayA 使用: "Technology/OS/Linux/Softwares/v2raya/v2raya.md"
          - Windows:
              - Windows tips: "Technology/OS/Windows/faq.md"
      - 浏览器:
          - Chrome 插件:
              - Google 输入工具: "Technology/Chrome-addons/google-input-tools.md"
              - Glarity: "Technology/Chrome-addons/glarity.md"
      - PDF 处理:
          - 给 PDF 文件添加目录: "Technology/PDF/Add-contents-to-a-PDF-file.md"
          - Sioyek 使用指南: "Technology/PDF/a-short-guide-of-sioyek.md"
      - 网络代理:
          - V2Ray+ws+tls+nginx(web) 全解析: "Technology/Proxy/v2ray-ws-tls-web.md"
          - Clash 订阅转换: "Technology/Proxy/clash-converter.md"
  - 学校课程:
      - Spring/Summer 2024:
          - 计算机组成与设计:
              - 1. Introduction: "School-Courses/SP-SU-2024/Computer-Organization-and-Design/1-Introduction.md"
              - 2. Arithmetics: "School-Courses/SP-SU-2024/Computer-Organization-and-Design/2-Arithmetics.md"
          - 数值分析:
              - 1. Introduction: "School-Courses/SP-SU-2024/Numerical-Analysis/1-introduction.md"
              - 2. Equations: "School-Courses/SP-SU-2024/Numerical-Analysis/2-equations.md"
              - 3. Linear Error Analysis: "School-Courses/SP-SU-2024/Numerical-Analysis/3-linear-error-analysis.md"
              - 4. Linear System: "School-Courses/SP-SU-2024/Numerical-Analysis/4-linear-system.md"
          - 拓扑数据处理:
              - 0. Foundamentals of TDA: "School-Courses/SP-SU-2024/TDA/lec0.md"
              - 1. Introduction: "School-Courses/SP-SU-2024/TDA/lec1.md"
              - 2.  Applications: "School-Courses/SP-SU-2024/TDA/lec2.md"
          - 数据库系统:
              - 1. Introduction: "School-Courses/SP-SU-2024/DBMS/1-Introduction.md"
              - 2. SQL Basics: "School-Courses/SP-SU-2024/DBMS/2-SQL-Basics.md"
              - 3. SQL Syntax: "School-Courses/SP-SU-2024/DBMS/3-SQL-Syntax.md"
              - 4. Advanced SQL: "School-Courses/SP-SU-2024/DBMS/4-Advanced-SQL.md"
          - ADS:
              - Inverted File Index: "School-Courses/SP-SU-2024/ADS/inverted-file-index.md"
  - 自学课程:
      - 2024 年:
          - EECS 498-007 / 598-005:
              - 0. PyTorch: "CS/24/dl4cv/0-pytorch.md"
              - 1. Introduction: "CS/24/dl4cv/1-introduction.md"
              - 2. Image Classification: "CS/24/dl4cv/2-image-classification.md"
              - 4. Optimization: "CS/24/dl4cv/4-optimization.md"
              - 5. Neural Networks: "CS/24/dl4cv/5-neural-networks.md"
              - 7. CNN: "CS/24/dl4cv/7-cnn.md"
              - 8. CNN Architectures: "CS/24/dl4cv/8-cnn-architectures.md"
              - 9. Hardware and Software: "CS/24/dl4cv/9-hardware-and-software.md"
              - 10-11. Training NN: "CS/24/dl4cv/10-11-training-nn.md"
          - CS 106L 课程:
              - 2. Types and Structs: "CS/24/Stanford-CS106L/2-Types-and-Structs.md"
              - 3. Initialization and References: "CS/24/Stanford-CS106L/3-Initialization-and-References.md"
              - 4. Streams: "CS/24/Stanford-CS106L/4-Streams.md"
              - 5. Containers: "CS/24/Stanford-CS106L/5-Containers.md"
              - 6. Iterators and Pointers: "CS/24/Stanford-CS106L/6-Iterators-and-Pointers.md"
              - 7. Classes: "CS/24/Stanford-CS106L/7-Classes.md"
              - 8. Template Classes and Const Correctness: "CS/24/Stanford-CS106L/8-Template-Classes-and-Const-Correctness.md"
              - 9. Template Functions: "CS/24/Stanford-CS106L/9-Template-Functions.md"
              - 10. Functions and Lambdas: "CS/24/Stanford-CS106L/10-Functions-and-Lambdas.md"
              - 11. Operators: "CS/24/Stanford-CS106L/11-Operators.md"
              - 12. Special Member Functions: "CS/24/Stanford-CS106L/12-Special-Member-Functions.md"
              - 13. Move Semantics: "CS/24/Stanford-CS106L/13-Move-Semantics.md"
              - 14. std::optional and Type Safety: "CS/24/Stanford-CS106L/14-std-optional-and-Type-Safety.md"
              - 15. RAII, Smart Pointers, and Building C++ Projects: "CS/24/Stanford-CS106L/15-RAII-Smart-Pointers-and-Building-CPP-Projects.md"
              - "Guest Lecture: Template Metaprogramming": "CS/24/Stanford-CS106L/GL-Template-Metaprogramming.md"
          - CS 15-445 课程:
              - 3-4. Database Storage: "CS/24/CMU-CS15-445/3-4-Database-Storage.md"
          - CSAPP 课程:
              - 1. Course Overview: "CS/24/CMU-CSAPP/1-Course-Overview.md"
              - 2-3. Bits, Bytes And Integers: "CS/24/CMU-CSAPP/2-3-Bits-Bytes-And-Integers.md"
              - 4. Floating Points: "CS/24/CMU-CSAPP/4-Floating-Points.md"
              - 5. Machine Level Programming - Basics: "CS/24/CMU-CSAPP/5-MLP-Basics.md"
              - 6. Machine Level Programming - Control: "CS/24/CMU-CSAPP/6-MLP-Control.md"
              - 7. Machine Level Programming - Procedure: "CS/24/CMU-CSAPP/7-MLP-Proc.md"
              - 8. Machine Level Programming - Data: "CS/24/CMU-CSAPP/8-MLP-Data.md"
              - 9. Machine Level Programming - Advanced: "CS/24/CMU-CSAPP/9-MLP-Advanced.md"
              - 10. Program Optimization: "CS/24/CMU-CSAPP/10-Program-Optimization.md"
              - 11. The Memory Hierarchy: "CS/24/CMU-CSAPP/11-The-Memory-Hierarchy.md"
              - 12. Cache Memories: "CS/24/CMU-CSAPP/12-Cache-Memories.md"
              - 13. Linking: "CS/24/CMU-CSAPP/13-Linking.md"
              - 14. Exceptional Control Flow - Exceptions and Processes: "CS/24/CMU-CSAPP/14-ECF-Exceptions-And-Processes.md"
              - 15. Exceptional Control Flow - Signals and Nonlocal Jumps: "CS/24/CMU-CSAPP/15-ECF-Signals-And-Nonlocal-Jumps.md"
              - 16. System-Level I/O: "CS/24/CMU-CSAPP/16-System-Level-IO.md"
              - 17. Virtual Memory: "CS/24/CMU-CSAPP/17-Virtual-Memory.md"
              - 18. Virtual Memory System: "CS/24/CMU-CSAPP/18-Virtual-Memory-System.md"
              - 19-20. Storage Allocation: "CS/24/CMU-CSAPP/19-20-Storage-Allocation.md"
              - 21-22. Network Programming: "CS/24/CMU-CSAPP/21-22-Network-Programming.md"
          - GAMES101 课程:
              - 12. Geometry: "CS/24/GAMES101/12-Geometry.md"
              - 13. Ray Tracing 1: "CS/24/GAMES101/13-Ray-Tracing-1.md"
              - 14-16. Ray Tracing 2-4: "CS/24/GAMES101/14-16-Ray-Tracing-2-4.md"
              - 17. Materials and Appearances: "CS/24/GAMES101/17-Materials-And-Appearances.md"
              - 19. Cameras, Lenses And Light Fields: "CS/24/GAMES101/19-Cameras-Lenses-And-Light-Fields.md"
              - 20. Color And Perception: "CS/24/GAMES101/20-Color-And-Perception.md"
              - 21-22. Animation: "CS/24/GAMES101/21-22-Animation.md"
          - PKU 编程语言理论:
              - 0+. OCaml Basics: "CS/24/PKU-PLT/ch0+.md"
              - 1-2. Introduction: "CS/24/PKU-PLT/ch1-2.md"
              - 3. Untyped Arithmetic Expressions: "CS/24/PKU-PLT/ch3.md"
              - 4. Lambda Calculus: "CS/24/PKU-PLT/ch4.md"
          - NJU 软件分析:
              - 1. Introduction: "CS/24/static-program-analysis/1-introduction.md"
              - 2. Intermediate Representation: "CS/24/static-program-analysis/2-intermediate-representation.md"
              - 3. Data Flow Analysis I: "CS/24/static-program-analysis/3-data-flow-analysis-i.md"
              - 4. Data Flow Analysis II: "CS/24/static-program-analysis/4-data-flow-analysis-ii.md"
          - USTC 计网:
              - 1. Introduction: "CS/24/USTC-Computer-Networking/1-Introduction.md"
              - 2. Application Layer: "CS/24/USTC-Computer-Networking/2-Application-Layer.md"
              - 3. Transport Layer: "CS/24/USTC-Computer-Networking/3-Transport-Layer.md"
  - 计算机科学:
      - 2023 年:
          - 图灵机代码: "CS/23/codes-for-turing-machine.md"
          - 和 ChatGPT 的一次交流: "CS/23/chatgpt-mutual-communication.md"
          - 神经网络简介: "CS/23/introduction-to-neuron-network/introduction-to-neuron-network.md"
          - 如何阅读源码: "CS/23/how-to-read-source-code.md"
  - 数学:
      - 2023 年:
          - MIT牛人解说数学体系: "Mathematics/23/mathematical-system-explained-by-MIT-master.md"
          - 图解对偶映射: "Mathematics/23/dual-map-explained.md"
          - Youtube 的数学频道: "Mathematics/23/math-channels-on-youtube.md"
          - 知乎用户收集: "Mathematics/23/good-users-on-zhihu.md"
  - 随记:
      - 2023 年:
          - 学习常用网站: "Notes/23/often-used-websites-in-study.md"
          - 关于在 Chatgpt 上执行代码: "Notes/23/run-code-on-chat-gpt.md"
          - 如何高效阅读论文: "Notes/23/how-to-read-papers-efficiently.md"
          - 如何祛费拉化: "Notes/23/how-to-not-be-a-fellah.md"
      - 2024 年:
          - 模拟计算: "Notes/24/analog-computing.md"
  - 转载:
      - Hostloc:
          - 樱花妹 (NSFW): "Repost/hostloc/23-10-08.md"
      - 知乎:
          - 库，框架，架构，平台的区别: "Repost/zhihu/distinguish-between-library-framework-architecture-platform.md"
          - 拓扑数据分析 - 持续同调:
              - 一: "Repost/zhihu/topological-data-analysis/topological-data-analysis-homology (1).md"
              - 二: "Repost/zhihu/topological-data-analysis/topological-data-analysis-homology (2).md"
              - 三: "Repost/zhihu/topological-data-analysis/topological-data-analysis-homology (3).md"
              - 四: "Repost/zhihu/topological-data-analysis/topological-data-analysis-homology (4).md"
              - 五（上）: "Repost/zhihu/topological-data-analysis/topological-data-analysis-homology (5a).md"
              - 五（下）: "Repost/zhihu/topological-data-analysis/topological-data-analysis-homology (5b).md"
          - 什么是代数: "Repost/zhihu/what-is-algebra.md"
          - 论数学教育: "Repost/zhihu/on-teaching-mathematics-v-i-arnold.md"
          - 个人谈 中西方一起在工业化上撒的慌: "Repost/zhihu/lies-that-china-and-the-west-have-made.md"
      - 哲学:
          - 汉哲学:
              - 文化危机: "Repost/philosophy/han-philosophy/cultural-crisis.md"
              - 传统汉文明的基本特征: "Repost/philosophy/han-philosophy/basic-characteristics-of-traditional-han-civilization.md"
      - 其它:
          - 开源推荐: "Repost/others/open-source-recommendation.md"
  - 音乐:
      - 特辑：前苏联:
          - 加盟共和国国歌选: "Music/USSR/national-anthems-of-union-republics.md"
      - 阿富汗: "Music/Afghanistan.md"
      - 伊朗: "Music/Iran.md"
      - 高加索:
          - 阿塞拜疆: "Music/Caucasia/Azerbaijan.md"
      - 中亚五国: "Music/Central-asia.md"
  - 美食:
      - 意大利:
          - Bolognese Sauce (番茄肉酱): "food/italy/bolognese-sauce.md"
          - Spaghetti Carbonara (培根蛋酱意大利面): "food/italy/spaghetti-carbonara.md"
          - Spaghetti al Limone: "food/italy/spaghetti-al-limone.md"
          - 如何选择意面: "food/italy/best-pasta-to-buy-in-store.md"

theme:
  name: "material"
  palette: #切换昼夜模式的颜色，审美差就用默认，专业点就自定义
    - media: "(prefers-color-scheme: light)"
      scheme: default #配色方案：浅色模式
      primary: Brown #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      accent: Brown #强调色，默认蓝，可以交互的元素如悬停链接、按钮和滚动条
      toggle:
        icon: material/weather-sunny #图标，太阳
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate #配色方案：深色模式
      # primary: Brown  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      toggle:
        icon: material/weather-night #图标，月亮
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tabs
  custom_dir: overrides

plugins:
  - search
  - mermaid2
  - encryptcontent:
      # use_secret: 'ENCRYPTCONTENT_PASSWORD'
      remember_password: True
      title_prefix: "[LOCKED]"
      summary: "This content is PROTECTED"
      encryption_info_message: "Contact me for access to this page."
  - toc:
      title: On this page
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
