site_name: M.T.Dickens' Blog
site_url: "https://blog.mtds.eu.org"
site_author: "mtdickens"
site_description: "mtdicken's blog"

nav:
  - 主页 Home: 'index.md'
  - 其他 Others:
    - 故障排除 Trouble Shooting: 
      - Cloudflare Pages 部署: 'Trouble Shooting/Cloudflare Pages deployment.md'
      - Ubuntu 中更改 Shell: 'Trouble Shooting/change shell in Ubuntu.md'
    - 使用技巧 Tips:
      - Linux: 'Tips/Linux tips.md'
      - Git: 'Tips/Git tips.md'
      - PDF:
        - 给 PDF 文件添加目录 Add contents to a PDF file: 'Tips/PDF/Add_contents_to_a_PDF_file.md'
  - 建议 Advice:
    - 教授建议 Professors:
      - 丁尧相教授 Prof. Yaoxiang Ding:
        - 阅读建议 Advice on Reading: 'Advice/Professors/Yaoxiang Ding/advice on reading.md'
        - 听讲记录 note: 'Advice/Professors/Yaoxiang Ding/note.md'

theme:
  name: 'material'
  palette:     #切换昼夜模式的颜色，审美差就用默认，专业点就自定义
    - media: "(prefers-color-scheme: light)" 
      scheme: default  #配色方案：浅色模式
      primary: Brown  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      accent: Brown  #强调色，默认蓝，可以交互的元素如悬停链接、按钮和滚动条
      toggle:
        icon: material/weather-sunny #图标，太阳
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  
      scheme: slate  #配色方案：深色模式
      # primary: Brown  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      toggle:
        icon: material/weather-night  #图标，月亮
        name: Switch to light mode

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
